name: Test

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  pull_request:
    branches:
      - master

# 这个工作流程需要执行的任务
jobs:
  flutter_test:
    name: Run flutter  build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v2.14.0
        with:
          channel: "stable"
      - run: flutter pub get
      # 执行测试
      - run: flutter test
      # 打包 APK
      - run: flutter build apk --release
      # 发布到 Release
