name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter  build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: "11.x"
        distribution: 
          java-package: "jdk"
      - uses: subosito/flutter-action@v2.14.0
        with:
          channel: "stable"
      - run: flutter pub get
      # 执行测试
      - run: flutter test
      # 打包 APK
      - run: flutter build apk --release
      # 发布到 Release
